apiVersion: v1
kind: Service
metadata:
  name: spotify-clone-mobile-loadbalancer
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: spotify-clone-mobile-statefulset-0
  ports:
  - port: 4411
    targetPort: 27017
