apiVersion: v1
kind: Service
metadata:
  name: spotify-clone-mobile-loadbalancer
spec:
  type: LoadBalancer
  selector:
    name: spotify-clone-mobile-backend
  ports:
  - port: 80
    targetPort: 80
