apiVersion: v1
kind: Service
metadata:
  labels:
    app: spotifycloneheadlessservice
  name: spotifycloneheadlessservice
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: spotifyclonestatefulset
  sessionAffinity: None
  type: ClusterIP
